### ISSUE TITLE
Seemingly Incorrect Weather Seed

### ISSUE THREAD

**Issue by Code-You-Fools** [averne/Turnips#41]
NHSE reports my weather seed as 3094284549, while Turnips reports it as 946800901 (0x386f0905). Trying both on MeteoNook seems to show that they're identical (I checked Yearly, Overview, and Monthly for May 2021), so I'm unsure what, exactly, is causing this, or if it even matters.

For the record, my game version is 1.10.0, and Turnips reports version 1.16.10-b96eb66.

**Comment by Code-You-Fools** [comment]
No worries. Sorry it took me so long, got hit by a bad storm the other night that knocked out my internet.
[ACNH.zip](https://github.com/averne/Turnips/files/6469863/ACNH.zip)

**Comment by averne** [comment]
No problem.
It seems NHSE presents the "raw" seed, while my program shows the seed after being "clamped" into a certain range (see [here](https://github.com/averne/Turnips/blob/master/src/parser.hpp#L358) and [here](https://github.com/Treeki/MeteoNook/blob/master/js/components/ForecastConfig.vue#L22)).
I assume that meteonook clamps the seed itself in case it's outside of the acceptable range, which is why the results are the same.

**Comment by Code-You-Fools** [comment]
Ah, I see. Thanks for looking into this - like I said in the initial report, it didn't *seem* to change anything about the weather since MeteoNook displayed the same Monthly and Yearly weather report for both seeds, but I just wanted to be sure.
